default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: flutter_backend-mysql-1 
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: group3_development

test:
  <<: *default
  database: group3_test

production:
  <<: *default
  database: group3_production
  
